version: "3.3"
services:
    db:
        image: postgres
        container_name: db
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        network_mode: host
    
    api:
        image: nginx:latest
        container_name: api
        volumes:
            - ./api/public:/var/www/html/public:rw    
            # - ./infra/default.conf:/etc/nginx/conf.d/default.conf
        network_mode: host
        # command: systemctl restart nginx
        
