version: "3.3"
services:
    db:
        image: mysql
        container_name: db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        network_mode: host
    
    api:
        build: 
            context: .
            dockerfile: infra/Dockerfile.symfony
        container_name: api
        volumes:
            - ./api:/api:rw    
        network_mode: host
        
