FROM php:7.4-fpm

COPY infra/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY infra/api_dev_init.sh /tmp/api_dev_init.sh

RUN  chmod +x /tmp/api_dev_init.sh &&\
     /bin/bash /tmp/api_dev_init.sh

WORKDIR /api

CMD symfony server:start
